repos:
  # General checks
  - repo: local
    hooks:
      - name: Prevent committing to main
        id: no-commit-to-branch
        language: system
        entry: no-commit-to-branch
        args: [--branch, main]
        pass_filenames: false
      - name: Make sure files end with a newline character
        id: end-of-file-fixer
        language: system
        entry: end-of-file-fixer
        types: [text]
      - name: Remove trailing whitespace
        id: trailing-whitespace-fixer
        language: system
        entry: trailing-whitespace-fixer
        types: [text]
      - name: Check for files that would conflict on case-insensitive filesystem
        id: check-case-conflict
        language: system
        entry: check-case-conflict
      - name: Check for merge conflicts
        id: check-merge-conflict
        language: system
        entry: check-merge-conflict
      - name: Check executable files have a shebang
        id: check-executables-have-shebangs
        language: system
        entry: check-executables-have-shebangs
        types: [executable]
      - name: Check scripts with a shebang are executable
        id: check-shebang-scripts-are-executable
        language: system
        entry: check-shebang-scripts-are-executable
      - name: Don't allow adding large files
        id: check-added-large-files
        language: system
        entry: check-added-large-files

  # Python
  - repo: local
    hooks:
      - name: Format Python files
        id: python-format
        language: system
        entry: ruff format
        types: [python]
        pass_filenames: false
      - name: Sort Python files
        id: python-sort
        language: system
        entry: ssort downloader
        types: [python]
        pass_filenames: false
      - name: Check Python files
        id: python-check
        language: system
        entry: ruff check --fix
        types: [python]
        pass_filenames: false
      - name: Type check Python files
        id: python-type-check
        language: system
        entry: basedpyright
        types: [python]
        pass_filenames: false

  # YAML
  - repo: local
    hooks:
      - name: Format YAML files
        id: yaml-format
        language: system
        entry: prettier --write
        types: [yaml]

  # Markdown
  - repo: local
    hooks:
      - name: Format markdown files
        id: markdown-format
        language: system
        entry: prettier --write
        types: [markdown]

  # GitHub Actions
  - repo: local
    hooks:
      - name: Validate GitHub Actions workflow files
        id: github-workflows-check
        language: system
        entry: actionlint
        types: [yaml]
        files: \.github/workflows/.*\.ya?ml$
      - name: Check GitHub Actions are pinned
        id: github-workflows-check-pinned
        language: system
        entry: ratchet check
        types: [yaml]
        files: \.github/workflows/.*\.ya?ml$

  # Nix
  - repo: local
    hooks:
      - name: Format Nix files
        id: nix-format
        language: system
        entry: nixfmt
        types: [nix]
